### ISSUE TITLE
IE crashes when notification is checked ?

### ISSUE THREAD

**Issue by Androc** [MichalVanzura/redmine_app_notifications#14]
Hello,

don't know if you saw that but on your redmine.org plugin's page (http://www.redmine.org/plugins/redmine_app_notifications), there is a  Mark Oliver Delos Reyes who wrote
> Tried testing on IE, the client notification when checked crashes IE.

You should ask to open an issue or to describe more because it seems very strange that the notification crashes IE.
I tried on IE8, Windows XP and IE11 Windows 8, I had no crash.

And I don't know how a simple JS could crash IE.

**Comment by MichalVanzura** [comment]
I would like to ask him to comment this issue. But there is no way how to write a comment to a plugin on redmine.org. And it seems that his user account is no longer on redmine.org. So i will leave this opened and maybe someone will write more.

**Comment by Androc** [comment]
Even the author of the plugin can answer ? Too bad :(

The user account exists but on redmine.org you can't see accounts (try with mine or yours, it is the same behavior).

I highly doubt that your plugin can crash the browser, even if it is Internet Explorer, but you are right, maybe you can leave this issue open, just in case.

**Comment by Androc** [comment]
It won't be solved as I am pretty sure it is not a real issue.
