### ISSUE TITLE
Default "viewed notifications" unchecked?

### ISSUE THREAD

**Issue by maiconzucco** [MichalVanzura/redmine_app_notifications#15]
Hi,

It's possible to make default unchecked the option "viewed notifications" on page app-notifications?
Like the image above:
![screen shot 2015-02-26 at 15 07 38](https://cloud.githubusercontent.com/assets/1846830/6398277/3eca06e2-bdc9-11e4-9c97-907965ef9c65.png)
Thanks.

**Comment by Androc** [comment]
I was thinking about that since the beginning I use this plugin.
Makes sense.
I will make a pull request tomorrow for this.

**Comment by maiconzucco** [comment]
Thanks @Androc.
My team really liked the plugin

**Comment by Androc** [comment]
The pull request #16 does the trick. If the author accepts it, you will be able to have the behaviour you want.
Or you can see what the changeset is (it is trivial : aa559beed8f89c5f0b205b96396873993b104b6f) and modify yourself, then restart your apache.

**Comment by maiconzucco** [comment]
Hi @Androc,

The trick is what I needed. Thanks.
Thanks for the information about IE.

**Comment by Androc** [comment]
No problem :)
