### ISSUE TITLE
User avatar

### ISSUE THREAD

**Issue by cheoAlejo** [MichalVanzura/redmine_app_notifications#19]
Great plugin.
It would be nice if we could see the avatar of the user who made the update, like in facebook.

![2015-06-18 14_30_16-facebook](https://cloud.githubusercontent.com/assets/10518807/8240232/bcd4c798-15c6-11e5-87ac-9809bc706ec0.png)

**Comment by Androc** [comment]
Hello,

it could be a good idea. Don't know if it is hard to achieve.
Thanks for your contributing.

**Comment by Androc** [comment]
Is it what you would want ?

![2015-06-19_11h35_51](https://cloud.githubusercontent.com/assets/400567/8251210/e0be633a-167a-11e5-923f-9d7e47707d5d.png)
Desktop notification
![2015-06-19_11h36_43](https://cloud.githubusercontent.com/assets/400567/8251211/e0c0244a-167a-11e5-8d72-7bc44812ff16.png)
Website notifications

@MichalVanzura I made a pull request but I am totally not sure if the modifications on ```app/models/app_notification.rb``` are legits (espececially the includes).

Warning : I did not test if the redmine instance has no gravatar, I will and fix it if it does not work.

**Comment by cheoAlejo** [comment]
Yes, that's cool. I just tried it and it works well. Is it safe to deploy to a production server ?

**Comment by Androc** [comment]
It is on my production server. It would be better if the author of the
plugin could validate that the code is clean as I am not a Ruby's expert
but otherwise I think it is safe

**Comment by MichalVanzura** [comment]
Thanks for an interesting idea. The code looks ok to me. Thank you @Androc for the pull request.

**Comment by Androc** [comment]
@MichalVanzura no problem, was glad to help :)
