### ISSUE TITLE
I don't receive notifications when issue is updated by email

### ISSUE THREAD

**Issue by Androc** [MichalVanzura/redmine_app_notifications#8]
I think this one is pretty tricky and I am too new to redmine/ruby to evaluate if it is possible or not.

I have many users who update their issues by email (using http://www.redmine.org/projects/redmine/wiki/RedmineReceivingEmails) and I don't receive notifications from them, only when a user updates issues from the website.

Do you think it is hard to add the possibility to hook on email updates ?

**Comment by Androc** [comment]
Apparently, you can use Rails callbacks : http://www.redmine.org/projects/redmine/wiki/Plugin_Internals#Using-Rails-callbacks-in-Redmine-plugins.

They give this example : https://github.com/edavis10/redmine_kanban/blob/000cf175795c18033caa43082c4e4d0a9f989623/init.rb#L10 https://github.com/edavis10/redmine_kanban/blob/000cf175795c18033caa43082c4e4d0a9f989623/lib/redmine_kanban/issue_patch.rb#L13
which I think is what I need to be sure to be notified whenever an issue is modified, regardless how.

I will try to found the solution myself but as I said, I am pretty new to Redmine/Ruby (I started both last week) so if you have time to help, would be great.

**Comment by MichalVanzura** [comment]
Yeah sure, I have already started working on this. Problem is that I am using Redmine controller hooks to create and send notifications. I will modify plugin to use Rails callbacks. Thanks for this issue as I did not even know about this receiving emails options in Redmine. I am also pretty new to Ruby and Redmine (I do not even use Redmine in production, this is my school project)

**Comment by Androc** [comment]
I am working on this issue on my side because I need it.

I found where your hooks are and that is exactly the problem described in the "Redmine hooks" example.

Let me know when you switched from Controller hooks to Rails callback as I use Redmine in production and your plugin is less usefull at the moment because many users update issues by email, so I miss these updates.

**Comment by MichalVanzura** [comment]
Plugin should now create and deliver a notification after every Issue or Journal create.

**Comment by Androc** [comment]
Nice ! I'm gonna check that right now :)

**Comment by MichalVanzura** [comment]
Thanks. I have not tested it, so let me know if it works.

**Comment by Androc** [comment]
It seems to work great ! Thanks a lot.
