### ISSUE TITLE
No task filter when plugin is installed

### ISSUE THREAD

**Issue by alternative4** [MichalVanzura/redmine_app_notifications#9]
It is a great plugin, but there is one big problem - I don't know, how it matters, but when I intsall plugin, my task filter block is empty:
![image](https://cloud.githubusercontent.com/assets/10988501/6183977/3111497c-b36d-11e4-8abb-b7f05da83324.png)
but when I remove plugin, I can filter tasks again: 
![image](https://cloud.githubusercontent.com/assets/10988501/6183990/56af25fa-b36d-11e4-8174-fb7ffc47d6ef.png)

System info:
Environment:
  Redmine version                2.6.0.stable.13653
  Ruby version                   1.9.3-p194 (2012-04-20) [i386-mingw32]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.5
  Git                            1.7.4

**Comment by Androc** [comment]
It is strange because there is "nothing" to do with filters. Maybe you have a JavaScript error which prevents the filter to display.

You should look :
* your JavaScript console
* the log of your Redmine to see if you have an error when displaying issues page

**Comment by alternative4** [comment]
Well, I agree - it is really strange, but it is this way. I didn't find any errors in log:

Started GET "/issues" for 172.22.116.149 at 2015-02-13 10:34:55 +0300
Processing by IssuesController#index as HTML
  Current user: daniel.kazakov (id=3)
  Rendered queries/_filters.html.erb (46.9ms)
  Rendered queries/_columns.html.erb (62.5ms)
  Rendered issues/_list.html.erb (343.7ms)
  Rendered plugins/redmine_loader/app/views/loader/_other_formats_builder.html.erb (0.0ms)
  Rendered issues/_sidebar.html.erb (15.6ms)
  Rendered issues/index.html.erb within layouts/base (531.2ms)
  Rendered plugins/redmine_app_notifications/app/views/app_notifications/_layouts_base_html_head.html.erb (0.0ms)
Completed 200 OK in 1671.8ms (Views: 734.3ms | ActiveRecord: 140.6ms)

I've tried from several workstations, and different browsers - the result is the same. When I have plugin - I have no filters. No plugin - filters. :)

**Comment by Androc** [comment]
I tried to disable JavaScript on my Redmine's installation and I had the same issue than you.
You should have a JavaScript error. Look at your JavaScript console, the answer should be there.

**Comment by Androc** [comment]
Your problem is probably a configuration problem : go to your Admin panel -> Plugins -> Redmine App Notifications plugin.
Is your Faye address valid and accessible from your browser ?
If not, the problem is there : if you want to use Faye server, you need to have a valid address.

**Comment by alternative4** [comment]
Faye adress is available, but responses with 400-Bad Request.
![image](https://cloud.githubusercontent.com/assets/10988501/6184501/9bda4b36-b373-11e4-8a56-c1115c3dd906.png)

**Comment by Androc** [comment]
You are facing the same problem as I had : by default, Faye server runs on loopback, this means it is available from your server (`Listening on 0.0.0.0:9292`).
You must provide a `-o your_server_name_or_ip` option after `-s thin`.
I think the README of the plugin should explain this.

**Comment by alternative4** [comment]
Actually, no. 0.0.0.0 means service is listening on all available interfaces...
Result is the same for now with -o option.

![image](https://cloud.githubusercontent.com/assets/10988501/6184589/d6388c92-b374-11e4-83cb-47ac1f878b2a.png)

**Comment by Androc** [comment]
The result is not the same as you have a Webpage not found. This means that your Faye server is unreachable. Maybe you have a firewall or something preventing your from accessing the 9292 port.
Try port 8080 (often proxy port, so firewalls allow this).

**Comment by alternative4** [comment]
Take a look at a previous screenshot - the same :-) HTTP 400 Bad Request in header, but "Webpage not found" in text - this is IE. :)

In chrome I get Bad Request as well
![image](https://cloud.githubusercontent.com/assets/10988501/6184685/32ef389a-b376-11e4-8878-1658fee25874.png)

**Comment by Androc** [comment]
Oh yeah, sorry did not pay enough attention :)

The "Bad Request" is "good news" as it means you can access your Faye server.

Did you try the plugin after using `-o` option ? The filter is still not there ?

**Comment by alternative4** [comment]
Yes, the picture is exactly the same... But if I turn of faye in plugin settings (empty URL) - I can see filters again ;)

**Comment by Androc** [comment]
Is your server on 172.25.8.122 the same as your Redmine one ?

Could you paste your JavaScript console errors ?

**Comment by alternative4** [comment]
Yes, it is the same. 

Finally, I've got this bug fixed - after I setup faye server IP address in plugin settings - everything works fine. With http://localhost:9292/faye, as it is mentioned in plugin description, it doesn't work.

I think plugin's description needs to be updated.

Thanks a lot for your help!

The JS error is listed further:
Navigated to http://redmine:3000/issues
issues:34 GET http://localhost:9292/faye/faye.js net::ERR_CONNECTION_REFUSED
issues:49 Uncaught ReferenceError: Faye is not definedissues:49 (anonymous function)jquery-1.11.1-ui-1.11.0-ujs-3.1.1.js?1416917242:2 m.Callbacks.jjquery-1.11.1-ui-1.11.0-ujs-3.1.1.js?1416917242:2 m.Callbacks.k.fireWithjquery-1.11.1-ui-1.11.0-ujs-3.1.1.js?1416917242:2 m.extend.readyjquery-1.11.1-ui-1.11.0-ujs-3.1.1.js?1416917242:2 J

PS. I also made Russian translation for this plugin and can share it, of needed

**Comment by Androc** [comment]
Yes, the README should be clearer on this point.
 In fact this issue is similar to the #4.

The default value of Faye address should be `http://server_ip_or_name:9292/faye`

The author of this plugin is cool, we will be certainly interested in your translation.

**Comment by alternative4** [comment]
Here is the translation (attached to this letter).

Fri Feb 13 2015 at 12:25:38, Androc <notifications@github.com>:

**Comment by Androc** [comment]
I think the attach failed. It should be easier to make a pull request to give translation.

**Comment by alternative4** [comment]
Done. Thanks a lot for your help.

**Comment by Androc** [comment]
No problem, have fun with the plugin and thanks for the translation :)
